name: steps-testing

on: 
  push:
    branches: '*'

jobs:
  build-id:
    runs-on: ubuntu-latest
    outputs:
      value_id: ${{ steps.version_data.outputs.version }}
    steps:
      - name: sample data
        id: version_data
        run: |
          echo "version=1.2.3" >> "$GITHUB_OUTPUT"

      - name: print outputs
        run: |
          echo "build version is ${{ steps.version_data.outputs.version}}"

  test-data:
    runs-on: ubuntu-slim
    needs: build-id
    steps:
      - name: demo
        run: |
          echo "job version id is ${{ needs.build-id.outputs.value_id }}"
